export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const PASS_SELECTED_ITEM = 'PASS_SELECTED_ITEM'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD '


export const CART_SELECT_SIZE = 'CART_SELECT_SIZE'
export const CART_DESELECT_SIZE = 'CART_DESELECT_SIZE'