const products = [
    {
        _id: '1',
        name: 'Nike Air Huarache',
        image: '/images/air-huarache.jfif',
        description: 'High Quality Shoes in your Area.',
        brand: 'Nike',
        category: 'Shoes',
        price: 200,
        countInstock: 5,
        rating: 5,
        numReviews: 5, 
        
    },
    {
        _id: '2',
        name: 'Nike Jordan Air',
        image: '/images/jordan-air.jfif',
        description: 'High Quality Shoes in your Area.',
        brand: 'Nike',
        category: 'Shoes',
        price: 250,
        countInstock: 8,
        rating: 4.5,
        numReviews: 9,
    },
    {
        _id: '3',
        name: 'Nike Blazer Low',
        image: '/images/nikeblazer-low.jfif',
        description: 'High Quality Shoes in your Area.',
        brand: 'Nike',
        category: 'Shoes',
        price: 259,
        countInstock: 10,
        rating: 4.9,
        numReviews: 32,
    },
    {
        _id: '4',
        name: 'Nike Blazer Low 77',
        image: '/images/nikeblazer-low-77.jfif',
        description: 'High Quality Shoes in your Area.',
        brand: 'Nike',
        category: 'Shoes',
        price: 270,
        countInstock: 8,
        rating: 4.5,
        numReviews: 9,
    },
    {
        _id: '5',
        name: 'Nike Court Legacy',
        image: '/images/nikecourt-legacy.jfif',
        description: 'High Quality Shoes in your Area.',
        brand: 'Nike',
        category: 'Shoes',
        price: 280,
        countInstock: 8,
        rating: 4.5,
        numReviews: 9,
    },
    {
        _id: '6',
        name: 'Nike Waffle One',
        image: '/images/nikewaffle-one.jfif',
        description: 'High Quality Shoes in your Area.',
        brand: 'Nike',
        category: 'Shoes',
        price: 270,
        countInstock: 8,
        rating: 4.5,
        numReviews: 9,
    },
    {
        _id: '7',
        name: 'Nike Winflo 8',
        image: '/images/nike-winflo.jfif',
        description: 'High Quality Shoes in your Area.',
        brand: 'Nike',
        category: 'Shoes',
        price: 270,
        countInstock: 8,
        rating: 4.5,
        numReviews: 9,
    },
    {
        _id: '8',
        name: 'Nike Air Zoom',
        image: '/images/nikeair-zoom.jfif',
        description: 'High Quality Shoes in your Area.',
        brand: 'Nike',
        category: 'Shoes',
        price: 270,
        countInstock: 8,
        rating: 4.5,
        numReviews: 9,
    },

    


]

export default products;